// This file is auto-generated, don't edit it. Thanks.
#ifndef ALIBABACLOUD_HA3MODEL_HPP_
#define ALIBABACLOUD_HA3MODEL_HPP_
#include <darabonba/Core.hpp>
#include <alibabacloud/models/Config.hpp>
#include <alibabacloud/models/SearchResponse.hpp>
#include <alibabacloud/models/QueryRequest.hpp>
#include <alibabacloud/models/Sort.hpp>
#include <alibabacloud/models/SparseData.hpp>
#include <alibabacloud/models/MultiQueryRequest.hpp>
#include <alibabacloud/models/FetchRequest.hpp>
#include <alibabacloud/models/RankQuery.hpp>
#include <alibabacloud/models/TextQuery.hpp>
#include <alibabacloud/models/SearchRequest.hpp>
#include <alibabacloud/models/AggFuncDesc.hpp>
#include <alibabacloud/models/OrderByDesc.hpp>
#include <alibabacloud/models/AggregateRequest.hpp>
#include <alibabacloud/models/BatchRequest.hpp>
#include <alibabacloud/models/PushDocumentsRequest.hpp>
#include <alibabacloud/models/PushDocumentsResponse.hpp>
#include <alibabacloud/models/ListTablesResponseBody.hpp>
#include <alibabacloud/models/ListTablesResponse.hpp>
#include <alibabacloud/models/GetTableResponseBody.hpp>
#include <alibabacloud/models/GetTableResponse.hpp>
#include <alibabacloud/models/CreateTableRequest.hpp>
#include <alibabacloud/models/CreateTableResponseBody.hpp>
#include <alibabacloud/models/CreateTableResponse.hpp>
#include <alibabacloud/models/ModifyTableRequest.hpp>
#include <alibabacloud/models/ModifyTableResponseBody.hpp>
#include <alibabacloud/models/ModifyTableResponse.hpp>
#include <alibabacloud/models/DeleteTableResponseBody.hpp>
#include <alibabacloud/models/DeleteTableResponse.hpp>
#include <alibabacloud/models/StopTableResponseBody.hpp>
#include <alibabacloud/models/StopTableResponse.hpp>
#include <alibabacloud/models/StartTableResponseBody.hpp>
#include <alibabacloud/models/StartTableResponse.hpp>
#include <alibabacloud/models/ReindexRequest.hpp>
#include <alibabacloud/models/ReindexResponseBody.hpp>
#include <alibabacloud/models/ReindexResponse.hpp>
#include <alibabacloud/models/ListTableGenerationsResponseBody.hpp>
#include <alibabacloud/models/ListTableGenerationsResponse.hpp>
#include <alibabacloud/models/GetTableGenerationResponseBody.hpp>
#include <alibabacloud/models/GetTableGenerationResponse.hpp>
#include <alibabacloud/models/ListTasksRequest.hpp>
#include <alibabacloud/models/ListTasksResponseBody.hpp>
#include <alibabacloud/models/ListTasksResponse.hpp>
#include <alibabacloud/models/ListTablesResponseBodyResult.hpp>
#include <alibabacloud/models/GetTableResponseBodyResultVectorIndexAdvanceParams.hpp>
#include <alibabacloud/models/GetTableResponseBodyResultVectorIndex.hpp>
#include <alibabacloud/models/GetTableResponseBodyResultDataSourceConfig.hpp>
#include <alibabacloud/models/GetTableResponseBodyResultDataSource.hpp>
#include <alibabacloud/models/GetTableResponseBodyResultDataProcessConfigParamsSrcFieldConfig.hpp>
#include <alibabacloud/models/GetTableResponseBodyResultDataProcessConfigParams.hpp>
#include <alibabacloud/models/GetTableResponseBodyResultDataProcessConfig.hpp>
#include <alibabacloud/models/GetTableResponseBodyResult.hpp>
#include <alibabacloud/models/CreateTableRequestVectorIndexAdvanceParams.hpp>
#include <alibabacloud/models/CreateTableRequestVectorIndex.hpp>
#include <alibabacloud/models/CreateTableRequestDataProcessConfigParamsSrcFieldConfig.hpp>
#include <alibabacloud/models/CreateTableRequestDataProcessConfigParams.hpp>
#include <alibabacloud/models/CreateTableRequestDataProcessConfig.hpp>
#include <alibabacloud/models/CreateTableRequestDataSourceConfig.hpp>
#include <alibabacloud/models/CreateTableRequestDataSource.hpp>
#include <alibabacloud/models/ModifyTableRequestDataProcessConfigParamsSrcFieldConfig.hpp>
#include <alibabacloud/models/ModifyTableRequestDataProcessConfigParams.hpp>
#include <alibabacloud/models/ModifyTableRequestDataProcessConfig.hpp>
#include <alibabacloud/models/ModifyTableRequestDataSourceConfig.hpp>
#include <alibabacloud/models/ModifyTableRequestDataSource.hpp>
#include <alibabacloud/models/ModifyTableRequestVectorIndexAdvanceParams.hpp>
#include <alibabacloud/models/ModifyTableRequestVectorIndex.hpp>
#include <alibabacloud/models/ListTableGenerationsResponseBodyResult.hpp>
#include <alibabacloud/models/GetTableGenerationResponseBodyResult.hpp>

#endif
